### ISSUE TITLE
Images don't load (404) when used with Immich v1.98.1

### ISSUE THREAD

**Issue by datatags** [agross/immich-duplicates#16]
When starting the duplicate browser, after entering the setup values and pressing OK, no images load. The browser network console shows many 404 errors, maybe caused by the removal of the "asset/assetById/{id}" endpoint? Immich 1.94.0 release notes mention that it would be removed in a future release, which seems to have happened.

**Comment by agross** [comment]
Yes, this is related to that breaking change in the Immich API.

**Comment by agross** [comment]
I don't know how to solve this ATM. The SDK package is months old and does not include [the new/replacement API](https://immich.app/docs/api/get-asset-info): https://www.npmjs.com/package/immich-sdk

**Comment by jrasm91** [comment]
Yes, we can work on updating the package.

**Comment by werkkrew** [comment]
So does this mean this tool is currently broken? Just want to know if I should bother installing it or wait for a fix because my Immic server is 1.98.x

**Comment by agross** [comment]
Yes, technically it's currently broken because of a mismatch between the `immich-sdk` package and what Immich 1.98 supports.

I was able to find a workaround that you may test. It only works 

* when you proxy the API calls through nginx, i.e.:

  ```sh
  docker container run \
                   --env IMMICH_URL=https://immich.example.com \
                   ghcr.io/agross/immich-duplicates-browser
  ```

* and you set `API Endpoint URL (including /api)` to the container's address like `http://localhost:8080/api` (but not your Immich instance).

Please `docker image pull ghcr.io/agross/immich-duplicates-browser` before testing.

If you see errors like `[error] 36#36: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53` then you need to add `--env NGINX_RESOLVER=<IP of your DNS server>` to the `docker container run` invocation.

Please report back.

**Comment by ckocyigit** [comment]
The immich-sdk-typescript-axios is deprecated and they have switched to openapi generation for the sdks.

I think you should switch to https://github.com/immich-app/immich/tree/main/open-api/typescript-sdk

I could look into switching the libs if I can find some time.

**Comment by agross** [comment]
@ckocyigit Ah, thank you, I wasn't aware "immich-sdk" is deprecated and "@immick/sdk" is the replacement. I've replaced the lib in 653255e. For me it solves the issue with images not loading.

@datatags @werkkrew Please test the updated docker image: `docker image pull ghcr.io/agross/immich-duplicates-browser`

**Comment by datatags** [comment]
Looks like that fixed it, thank you!!
